COLLEGE/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'COLLEGE'
urlpatterns =[

    path('',views.index,name='home'),
    path('login/',views.my,name='login'),
    # path('admin/',views.my,name='admin'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
path('',include('COLLEGE.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

COLLEGE/models.py
from django.db import models


class Post(models.Model):
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=100)
    date = models.DateField(auto_now=True,null=True,blank=True)
    img=models.ImageField(upload_to='add')

COLLEGE/views.py
from django.shortcuts import render, HttpResponse,redirect
from django.contrib.auth.models import auth,User
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render
def home(request):
    print('homepage')


def login(request):
    pass


from .models import Post


# ob1 = Post()
# ob2 = Post()
# ob3 = Post()
#
# ob1.name = 'arya'
# ob1.age = '22'
# ob1.date = '12.12.12'
#
# ob2.name='rishika'
# ob2.age='23'
# ob2.date='11.11.11'
#
# ob3.name='athulya'
# ob3.age='22'
# ob3.date='9.9.9'

# objects=[ob1,ob2,ob3]

def home(request):
    objects = Post.objects.all()
    recent=Post.objects.order_by('-date')[0:3]
    return render(request, 'marketing-index.html', {'ob': objects}),


def my(request):
    if request.method =='POST':
        a=request.POST['firstname']
        b=request.POST['lastname']
        user=auth.authenticate(username=a,password=b)
        if user is not None:
         auth.login(request,user)
         return redirect('COLLEGE:home')
        else:
          messages.error(request,'login error')
        return redirect('COLLEGE:login')
        print(request.POST)
        # return render(request,'marketing-index.html')
        return redirect('COLLEGE:home')
    return render(request, 'my.html')
def logout(request):
    auth.logout(request)
    return redirect('COLLEGE:home')
# def register(request):
#     return render(request, 'register.html')
def register(request):
    if request.method =='POST':
        a=request.POST['username']
        b=request.POST['email']
        c=request.POST['psw']
        d=request.POST['psw-repeat']
        if c==d:
            if User.objects.filter(username=a):
                messages.error(request,'username already exist')
                return redirect('COLLEGE:register')
            elif User.objects.filter(email=b):
                messages.error(request,'email exist')
            else:
              v=User.objects.create_user(username=a,email=b,password=c,is_staff=1,is_superuser=1)
              v.save()
        else:
            messages.error(request,'error')
            return redirect('COLLEGE:register')
        auth.login(request,v)
        print(a,b,c)
        return redirect('COLLEGE:home')
    return render(request,'register.html')



def index(request):
    if request.method =='POST':
        a=request.POST['username']
        b=request.POST['lastname']
        return render(request,'marketing-index.html')
    objects = Post.objects.all()
    recent = Post.objects.order_by('-date')[0:3]
    return render(request, 'marketing-index.html', {'obj': objects,
                                                    'res':recent})
def listing(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 2)

    page = request.GET.get('page')
    objects = paginator.get_page(page)
    return render(request, 'marketing-index.html', {'objects': objects})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% include 'head.html' %}
</head>
<body>
    {% include 'header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    {% include 'script.html' %}

</body>
</html>

templates/footer.html
{% load static %}
<footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="widget">
                            <h2 class="widget-title">Recent Posts</h2>
                            <div class="blog-list-widget">

                                <div class="list-group">
                                    {% for i in res %}
                                    <a href="{% static 'marketing-single.html' %}" class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="w-100 justify-content-between">
                                            <img src="{{ i.img.url }}" alt="" class="img-fluid float-left">
                                            <h5 class="mb-1">5 Beautiful buildings you need to before dying</h5>
                                            <small>12 Jan, 2016</small>
                                        </div>
                                    </a>
                                    {% endfor %}


<!--                                    <a href="{% static 'marketing-single.html' %}" class="list-group-item list-group-item-action flex-column align-items-start">-->
<!--                                        <div class="w-100 justify-content-between">-->
<!--                                            <img src="{% static 'upload/small_05.jpg' %}" alt="" class="img-fluid float-left">-->
<!--                                            <h5 class="mb-1">Let's make an introduction for creative life</h5>-->
<!--                                            <small>11 Jan, 2016</small>-->
<!--                                        </div>-->
<!--                                    </a>-->

<!--                                    <a href="{% static 'marketing-single.html' %}" class="list-group-item list-group-item-action flex-column align-items-start">-->
<!--                                        <div class="w-100 last-item justify-content-between">-->
<!--                                            <img src="{% static 'upload/small_06.jpg' %}" alt="" class="img-fluid float-left">-->
<!--                                            <h5 class="mb-1">Did you see the most beautiful sea in the world?</h5>-->
<!--                                            <small>07 Jan, 2016</small>-->
<!--                                        </div>-->
<!--                                    </a>-->
                                </div>

                            </div><!-- end blog-list -->
                        </div><!-- end widget -->
                    </div><!-- end col -->

                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="widget">
                            <h2 class="widget-title">Popular Posts</h2>
                            <div class="blog-list-widget">
                                <div class="list-group">
                                    <a href="{% static 'marketing-single.html' %}" class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="w-100 justify-content-between">
                                            <img src="{% static 'upload/small_01.jpg' %}" alt="" class="img-fluid float-left">
                                            <h5 class="mb-1">Banana-chip chocolate cake recipe with customs</h5>
                                            <span class="rating">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </span>
                                        </div>
                                    </a>

                                    <a href="{% static 'marketing-single.html' %}" class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="w-100 justify-content-between">
                                            <img src="{% static 'upload/small_02.jpg'%}" alt="" class="img-fluid float-left">
                                            <h5 class="mb-1">10 practical ways to choose organic vegetables</h5>
                                            <span class="rating">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </span>
                                        </div>
                                    </a>

                                    <a href="{% static 'marketing-single.html' %}" class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="w-100 last-item justify-content-between">
                                            <img src="{% static 'upload/small_03.jpg' %}" alt="" class="img-fluid float-left">
                                            <h5 class="mb-1">We are making homemade ravioli, nice and good</h5>
                                            <span class="rating">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </span>
                                        </div>
                                    </a>
                                </div>
                            </div><!-- end blog-list -->
                        </div><!-- end widget -->
                    </div><!-- end col -->

                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="widget">
                            <h2 class="widget-title">Popular Categories</h2>
                            <div class="link-widget">
                                <ul>
                                    <li><a href="{% static '#' %}">Marketing <span>(21)</span></a></li>
                                    <li><a href="{% static '#' %}">SEO Service <span>(15)</span></a></li>
                                    <li><a href="{% static '#' %}">Digital Agency <span>(31)</span></a></li>
                                    <li><a href="{% static '#' %}">Make Money <span>(22)</span></a></li>
                                    <li><a href="{% static '#' %}">Blogging <span>(66)</span></a></li>
                                    <li><a href="{% static '#' %}">Entertaintment <span>(11)</span></a></li>
                                    <li><a href="{% static '#' %}">Video Tuts <span>(87)</span></a></li>
                                </ul>
                            </div><!-- end link-widget -->
                        </div><!-- end widget -->
                    </div><!-- end col -->
                </div><!-- end row -->

                <div class="row">
                    <div class="col-md-12 text-center">
                        <br>
                        <br>
                        <div class="copyright">&copy; Markedia. Design: <a href="{% static 'http://html.design' %}">HTML Design</a>.</div>
                    </div>
                </div>
            </div><!-- end container -->
        </footer><!-- end footer -->

templates/head.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site Metas -->
    <title>Markedia - Marketing Blog Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

     Site Icons
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

    <!-- Design fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- FontAwesome Icons core CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'style.css' %}" rel="stylesheet">

    <!-- Animate styles for this template -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">

    <!-- Responsive styles for this template -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <!-- Colors for this template -->
    <link href="{% static 'css/colors.css' %}" rel="stylesheet">

    <!-- Version Marketing CSS for this template -->
    <link href="{% static 'css/version/marketing.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
</html>

templates/header.html
{% load static %}

<header class="market-header header">
            <div class="container-fluid">
                <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="{% static 'marketing-index.html' %}"><img src="{% static 'images/version/market-logo.png' %}" alt=""></a>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'COLLEGE:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% static 'marketing-category.html' %}">Marketing</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% static 'marketing-category.html' %}">Make Money</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% static 'marketing-blog.html' %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% static 'marketing-contact.html' %}">Contact Us</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'COLLEGE:logout' %} ">logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'COLLEGE:login' %} ">Login</a>
                            </li>

                             <li class="nav-item">
                                <a class="nav-link" href="{% url 'COLLEGE:register' %}">register</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="admin/">admin</a>
                            </li>

                        </ul>
                        <form class="form-inline">
                            <input class="form-control mr-sm-2" type="text" placeholder="How may I help?">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </nav>
            </div><!-- end container-fluid -->
        </header><!-- end market-header -->

templates/mewone.html
 <!DOCTYPE html>
 {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <style> body {background-color: black;}
            h1 {color: blue;
    text-align: center;
    font-family:Broadway;
    font-size: 85px;}
            h2 {color: black;text-align:center;margin:60px;}
            p  {color: green;text-align:center;}
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-12" style="background-image: url(https://getmyuni.azureedge.net/college-image/big/nehru-college-of-engineering-research-centre-thrissur-.jpg);">
            <div class="col-sm-4">
                        <img src="https://www.nehrucolleges.com/best-colleges-coimbatore-kerala/logo/ncerc.jpg" width="250" height="250" style="padding-top: 56px;">
            </div>
            <div class="col-sm-4">
                    <h1>BTECH</h1>
                    <h3 style="font-family:Bauhaus 93;color:white;text-align:center;">Admission started</h3>
            </div>
            <div class="col-sm-4">
                <form>
  <div class="form-group" >
      <h2>REGISTER</h2>
    <label for="email">Email address:</label>
    <input type="email" class="form-control" id="email">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
            </div>
        </div>
    </div>
</div>


<div class="container">
  <div class="row">
      <div class="col-sm-12" style="padding-top: 100px">
        <div class="col-sm-4">
            <a href="https://www.myklassroom.com/Engineering-branches/4/Electronics-&-Communication-Engg.-(ECE)">
           <h3>Electronics and communication engineering</h3></a>
            <a href="https://www.sofcontraining.com/best-job-oriented-courses-after-be-in-electronics-engineering.html">
                <p>For more....</p></a>
            <img src="http://www.nssce.ac.in/wp-content/uploads/2016/03/banner.jpg" width="250" height="250">
        </div>
        <div class="col-sm-4">
            <a href="https://s3.amazonaws.com/msoe/files/callouts/wide_sml_computer-science-landing-page.jpg">
            <h3>Computer science engineering</h3></a>
            <a href="https://s3.amazonaws.com/msoe/files/callouts/wide_sml_computer-science-landing-page.jpg">
                <p>For more....</p></a>
            <img src="https://s3.amazonaws.com/msoe/files/callouts/wide_sml_computer-science-landing-page.jpg" width="250" height="200">
         </div>
         <div class="col-sm-4">
            <a href="https://collegedunia.com/courses/bachelor-of-engineering-be-mechatronics-engineering">
            <h3>Mechanical engineering</h3></a>
             <a href="https://collegedunia.com/courses/bachelor-of-engineering-be-mechatronics-engineering"></a><p>For more....</p>
             <img src="https://career.webindia123.com/career/options/images/mechatronics.jpg" width="250" height="250">
         </div>
      </div>
  </div>
</div>









</body>
</html>

templates/my.html
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<br>
<br>
<br>
<h>login</h>
<form action="."method="post">
    {% csrf_token %}
  First name:<br>
  <input type="text" name="firstname" value="Arya">
  <br>
  Last name:<br>
  <input type="password" name="lastname" value="Arimbooth">
  <br><br>
  <input type="submit" value="Submit">
</form>
    {% for i in messages %}
    <h>{{ i }}</h>
    {% endfor %}
{% endblock content %}
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>
</head>
<body>

<form action="."method="post">
    {% csrf_token %}
  <div class="container">
    <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>

    <label for="username"><b>Username</b></label>
    <input type="text" placeholder="Username" name="username" required>

    <label for="email"><b>Email</b></label>
    <input type="email" placeholder="Enter Email" name="email" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
    <hr>
    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

    <button type="submit" class="registerbtn">Register</button>
  </div>

  <div class="container signin">
    <p>Already have an account? <a href="#">Sign in</a>.</p>
  </div>
</form>

</body>
</html>

templates/script.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/tether.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/animate.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>